# Generated by Django 5.1.8 on 2026-02-24 08:04

import books.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_hausa', models.CharField(max_length=100)),
                ('name_arabic', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name_hausa'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sunan Littafi (Larabci)')),
                ('title_hausa', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sunan Littafi (Hausa)')),
                ('author', models.CharField(max_length=300, verbose_name='Marubuci')),
                ('translator', models.CharField(blank=True, max_length=300, null=True, verbose_name='Mai Fassara')),
                ('category_specific', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ƙaramin Rukuni')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Bayani game da Littafi')),
                ('table_of_contents', models.JSONField(blank=True, default=list, verbose_name='Fihirisa')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Kalmomin Bincike')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('ha', 'Hausa'), ('en', 'English'), ('fr', 'Français')], default='ha', max_length=5)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Shekarar Bugu')),
                ('status', models.CharField(choices=[('draft', 'Daftari'), ('processing', 'Ana sarrafa'), ('published', 'An buga')], default='draft', max_length=20)),
                ('approved', models.BooleanField(default=False, verbose_name='An tabbatar ta hanyar ilimi')),
                ('file', models.FileField(blank=True, null=True, upload_to=books.models.book_file_path)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=books.models.book_cover_path)),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=500, null=True)),
                ('seo_slug', models.SlugField(blank=True, max_length=191, null=True, unique=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_books', models.ManyToManyField(blank=True, to='books.book', verbose_name='Littattafai masu alaƙa')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ha', max_length=5)),
                ('audio_file', models.FileField(upload_to=books.models.audio_file_path)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_versions', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reporter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('feedback_type', models.CharField(choices=[('error', 'Kuskure'), ('suggestion', 'Shawara'), ('translation', 'Fassara')], default='error', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ana jira'), ('reviewed', 'An duba'), ('resolved', 'An warware')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=191, unique=True)),
                ('source_site', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to=books.models.scraped_file_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='LLM analysis: is_islamic, confidence, suggested_category, reason')),
                ('status', models.CharField(choices=[('discovered', 'An gano'), ('verified', 'An tabbatar'), ('rejected', 'An ƙi'), ('imported', 'An shigo da shi'), ('failed', 'Ya gaza')], default='discovered', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_source', to='books.book')),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('twitter', 'Twitter/X'), ('facebook', 'Facebook')], max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='SovereignGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_arabic', models.CharField(max_length=200)),
                ('term_hausa', models.CharField(max_length=200)),
                ('term_english', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sovereign Glossary',
                'unique_together': {('term_arabic', 'term_hausa')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('total_pages', models.IntegerField(default=0)),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
    ]
