# Generated by Django 6.0.2 on 2026-02-25 08:38

from django.db import migrations, models


def create_default_languages(apps, schema_editor):
    Language = apps.get_model('books', 'Language')
    defaults = [
        {'code': 'ha', 'name_native': 'Hausa', 'name_english': 'Hausa', 'flag_emoji': '', 'direction': 'ltr', 'is_default': True, 'order': 1},
        {'code': 'ar', 'name_native': 'العربية', 'name_english': 'Arabic', 'flag_emoji': '', 'direction': 'rtl', 'order': 2},
        {'code': 'en', 'name_native': 'English', 'name_english': 'English', 'flag_emoji': '', 'direction': 'ltr', 'order': 3},
        {'code': 'am', 'name_native': 'አማርኛ', 'name_english': 'Amharic', 'flag_emoji': '', 'direction': 'ltr', 'order': 4},
    ]
    for data in defaults:
        Language.objects.update_or_create(code=data['code'], defaults=data)


def remove_default_languages(apps, schema_editor):
    Language = apps.get_model('books', 'Language')
    Language.objects.filter(code__in=['ha', 'ar', 'en', 'am']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_notification_readinglist_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO code e.g. ha, ar, en', max_length=10, unique=True)),
                ('name_native', models.CharField(max_length=100)),
                ('name_english', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=8, null=True)),
                ('direction', models.CharField(choices=[('ltr', 'Left-to-Right'), ('rtl', 'Right-to-Left')], default='ltr', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name_native'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('ha', 'Hausa'), ('en', 'English'), ('hr', 'الأمهري')], default='ha', max_length=5),
        ),
        migrations.RunPython(create_default_languages, remove_default_languages),
    ]
