# Generated by Django 6.0.2 on 2026-02-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_language_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='books.language'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_versions', to='books.language', to_field='code'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.language', to_field='code'),
        ),
    ]
