# Generated by Django 6.0.2 on 2026-02-25 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_category_language_alter_audioversion_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=191)),
                ('content', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_texts', to='books.language')),
            ],
            options={
                'verbose_name': 'Site Text',
                'verbose_name_plural': 'Site Texts',
                'ordering': ['key'],
                'unique_together': {('key', 'language')},
            },
        ),
    ]
