# Generated by Django 4.2.29 on 2026-03-10 10:39

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_sitetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioversion',
            name='audio_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط خارجي (Google Drive)'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=books.models.audio_file_path),
        ),
    ]
