# Generated by Django 4.2.29 on 2026-03-11 10:12

import books.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_audioversion_audio_url_alter_audioversion_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=books.models.profile_avatar_path, verbose_name='Hoton Fuska')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ƙasa')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Ranar Haihuwa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
