# Generated by Django 5.1.8 on 2026-05-04 09:25

import books.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_delete_scrapedbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioversion',
            options={'verbose_name': 'النسخة الصوتية', 'verbose_name_plural': 'النسخ الصوتية'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'الكتاب', 'verbose_name_plural': 'الكتب'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name_hausa'], 'verbose_name': 'التصنيف', 'verbose_name_plural': 'التصنيفات'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'التعليق', 'verbose_name_plural': 'التعليقات'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'المفضلة', 'verbose_name_plural': 'المفضلات'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'التقرير / الملاحظة', 'verbose_name_plural': 'التقارير والملاحظات'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['order', 'name_native'], 'verbose_name': 'اللغة', 'verbose_name_plural': 'اللغات'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'الإشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AlterModelOptions(
            name='readinglist',
            options={'verbose_name': 'قائمة القراءة', 'verbose_name_plural': 'قوائم القراءة'},
        ),
        migrations.AlterModelOptions(
            name='readingprogress',
            options={'verbose_name': 'تقدم القراءة', 'verbose_name_plural': 'تقدم القراءة'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'التقييم', 'verbose_name_plural': 'التقييمات'},
        ),
        migrations.AlterModelOptions(
            name='searchlog',
            options={'verbose_name': 'سجل البحث', 'verbose_name_plural': 'سجلات البحث'},
        ),
        migrations.AlterModelOptions(
            name='sitetext',
            options={'ordering': ['key'], 'verbose_name': 'النص الثابت', 'verbose_name_plural': 'النصوص الثابتة'},
        ),
        migrations.AlterModelOptions(
            name='socialpost',
            options={'verbose_name': 'منشور التواصل الاجتماعي', 'verbose_name_plural': 'منشورات التواصل الاجتماعي'},
        ),
        migrations.AlterModelOptions(
            name='sovereignglossary',
            options={'verbose_name': 'مصطلح ديني', 'verbose_name_plural': 'المصطلحات الدينية (Glossary)'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'الملف الشخصي للمستخدم', 'verbose_name_plural': 'الملفات الشخصية للمستخدمين'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_amharic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالأمهرية'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_swahili',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالسواحيلية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=books.models.audio_file_path, verbose_name='ملف الصوت'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_versions', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='duration_seconds',
            field=models.IntegerField(default=0, verbose_name='المدة بالثواني'),
        ),
        migrations.AlterField(
            model_name='audioversion',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_versions', to='books.language', to_field='code', verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='موافق عليه علمياً'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=300, verbose_name='المؤلف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category_specific',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='التصنيف الفرعي'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.book_cover_path, verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='download_count',
            field=models.IntegerField(default=0, verbose_name='عدد التحميلات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=books.models.book_file_path, verbose_name='ملف الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.language', to_field='code', verbose_name='لغة الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, to='books.book', verbose_name='كتب ذات صلة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='وصف السيو (SEO)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seo_slug',
            field=models.SlugField(blank=True, max_length=191, null=True, unique=True, verbose_name='الرابط الدائم (Slug)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان السيو (SEO)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('processing', 'جاري المعالجة'), ('published', 'تم النشر')], default='draft', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='book',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, verbose_name='الفهرس'),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='الكلمات الدلالية'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500, verbose_name='اسم الكتاب (العربية)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_hausa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اسم الكتاب (الهوسا)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='المترجم'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة النشر'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='books.language', verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم الأساسي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_arabic',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_hausa',
            field=models.CharField(max_length=100, verbose_name='الاسم بلغة الهوسا'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='الرابط (Slug)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='محتوى التعليق'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='books.comment', verbose_name='الرد على'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('error', 'خطأ'), ('suggestion', 'اقتراح'), ('translation', 'ترجمة')], default='error', max_length=20, verbose_name='نوع الملاحظة'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني للمبلّغ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المبلّغ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('reviewed', 'تمت المراجعة'), ('resolved', 'تم الحل')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='كود اللغة (ISO)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='language',
            name='direction',
            field=models.CharField(choices=[('ltr', 'من اليسار إلى اليمين (LTR)'), ('rtl', 'من اليمين إلى اليسار (RTL)')], default='ltr', max_length=3, verbose_name='اتجاه النص'),
        ),
        migrations.AlterField(
            model_name='language',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='رمز العلم (Emoji)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='language',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='لغة افتراضية'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_english',
            field=models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name_native',
            field=models.CharField(max_length=100, verbose_name='الاسم الأصلي'),
        ),
        migrations.AlterField(
            model_name='language',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_book', 'كتاب جديد'), ('review_reply', 'رد على تقييم'), ('comment_reply', 'رد على تعليق'), ('feedback_update', 'تحديث ملاحظة')], max_length=20, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='in_lists', to='books.book', verbose_name='الكتب'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='عامة'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم القائمة'),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=1, verbose_name='الصفحة الحالية'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='last_read',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر قراءة'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='total_pages',
            field=models.IntegerField(default=0, verbose_name='إجمالي الصفحات'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, verbose_name='محتوى التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان التقييم'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البحث'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='query',
            field=models.CharField(max_length=500, verbose_name='نص البحث'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='results_count',
            field=models.IntegerField(default=0, verbose_name='عدد النتائج'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='content',
            field=models.TextField(verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وصف داخلي'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.CharField(max_length=191, verbose_name='مفتاح النص (Key)'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_texts', to='books.language', verbose_name='اللغة'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='books.book', verbose_name='الكتاب'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('telegram', 'تيليجرام'), ('twitter', 'تويتر (X)'), ('facebook', 'فيسبوك')], max_length=20, verbose_name='المنصة'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='post_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معرف المنشور'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='success',
            field=models.BooleanField(default=True, verbose_name='تم بنجاح'),
        ),
        migrations.AlterField(
            model_name='sovereignglossary',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='sovereignglossary',
            name='definition',
            field=models.TextField(blank=True, null=True, verbose_name='التعريف'),
        ),
        migrations.AlterField(
            model_name='sovereignglossary',
            name='term_arabic',
            field=models.CharField(max_length=200, verbose_name='المصطلح بالعربي'),
        ),
        migrations.AlterField(
            model_name='sovereignglossary',
            name='term_english',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المصطلح بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='sovereignglossary',
            name='term_hausa',
            field=models.CharField(max_length=200, verbose_name='المصطلح بالهوسا'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=books.models.profile_avatar_path, verbose_name='الصورة الشخصية'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الدولة'),
        ),
    ]
