from django.core.management.base import BaseCommand
from books.models import Book, Category


class Command(BaseCommand):
    help = 'Seed sample books with rich data for display'

    def handle(self, *args, **options):
        # Get categories
        cats = {}
        for slug in ['aqeedah', 'hadith', 'fiqh', 'tafsir', 'seerah', 'tazkiyah', 'arabic', 'usul-al-fiqh']:
            cats[slug] = Category.objects.filter(slug=slug).first()

        books_data = [
            # ══════════════════════════════════════════
            # العقيدة - AQEEDAH (5 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'كتاب التوحيد',
                'title_hausa': 'Littafin Tauhidi',
                'author': 'محمد بن عبد الوهاب',
                'translator': 'شيخ أبو بكر محمود غومي',
                'category': cats['aqeedah'],
                'category_specific': 'Tawheed',
                'description': 'Wannan littafi ne na asali a cikin ilimin tauhidi. Sheikh Muhammad ibn Abdul-Wahhab ya rubuta shi don bayyana ma\'anar tauhidi da kadaita Allah cikin ibada. Ya kunshi surori 67 da suka fara daga ma\'anar tauhidi, falallarsa, da kuma bayyana shirka da hanyoyin da ake kaucewa ta. Kowane babi yana dauke da ayoyin Alkur\'ani da hadisan Annabi (SAW) a matsayin dalili.',
                'table_of_contents': ['Babi na 1: Ma\'anar Tauhidi', 'Babi na 2: Falalar Tauhidi', 'Babi na 3: Wanda ya cika Tauhidi', 'Babi na 4: Tsoron Shirka', 'Babi na 5: Kiran zuwa ga Shahada', 'Babi na 6: Tafsirin Tauhidi da Shahadar La ilaha illallah', 'Babi na 7: Sa Layar kariya da Tama\'in', 'Babi na 8: Ruqya da Tama\'in', 'Babi na 9: Riya\'u', 'Babi na 10: Bautawa ba Allah ba'],
                'tags': ['tauhidi', 'akida', 'shirka', 'ibada', 'sheikh muhammad', 'kadaita allah', 'monotheism', 'kitab al-tawhid', 'aqeedah'],
                'language': 'ha', 'year': 1740, 'status': 'published', 'approved': True,
                'seo_slug': 'littafin-tauhidi',
                'seo_title': 'Littafin Tauhidi - Kitab al-Tawhid na Hausa',
                'seo_description': 'Littafin Tauhidi na Sheikh Muhammad ibn Abdul-Wahhab. Bayyanin tauhidi da kadaita Allah cikin ibada a harshen Hausa.',
                'view_count': 1250, 'download_count': 430,
            },
            {
                'title': 'العقيدة الواسطية',
                'title_hausa': 'Akidar Wasitiyya',
                'author': 'ابن تيمية',
                'translator': 'الشيخ جعفر محمود آدم',
                'category': cats['aqeedah'],
                'category_specific': 'Creed',
                'description': 'Daya daga cikin muhimman littattafan akida da Sheikh al-Islam Ibn Taymiyyah ya rubuta. Yana bayyana akidar Ahlus-Sunnah wal-Jama\'ah game da sunayen Allah da siffofinSa, da imani da mala\'iku, littattafai, manzanni, da ranar lahira. Littafi ne gajere amma ya tattara muhimman batutuwan akida.',
                'table_of_contents': ['Gabatarwa: Akidar Ahlus-Sunnah', 'Babi na 1: Siffofin Allah a Alkur\'ani', 'Babi na 2: Kalmar Allah', 'Babi na 3: Ganin Allah Ranar Kiyama', 'Babi na 4: Imani da Mala\'iku', 'Babi na 5: Imani da Littattafai', 'Babi na 6: Imani da Manzanni', 'Babi na 7: Imani da Ranar Karshe', 'Babi na 8: Al-Qadr (Kaddara)', 'Babi na 9: Matsayin Sahabbai'],
                'tags': ['akida', 'ibn taymiyyah', 'sunnah', 'siffofi', 'imani', 'wasitiyya', 'creed', 'aqeedah'],
                'language': 'ha', 'year': 1306, 'status': 'published', 'approved': True,
                'seo_slug': 'akidar-wasitiyya',
                'seo_title': 'Akidar Wasitiyya - Ibn Taymiyyah na Hausa',
                'seo_description': 'Akidar Wasitiyya na Ibn Taymiyyah. Bayyanin akidar Ahlus-Sunnah game da sunayen Allah da siffofinSa.',
                'view_count': 890, 'download_count': 310,
            },
            {
                'title': 'ثلاثة الأصول وأدلتها',
                'title_hausa': 'Tushe Uku da Dalillansu',
                'author': 'محمد بن عبد الوهاب',
                'category': cats['aqeedah'],
                'category_specific': 'Fundamentals',
                'description': 'Gajeriyar risala ce mai muhimmanci da ta kunshi tushe uku da kowane musulmi ya kamata ya san su: sanin Ubangijinka, sanin addininsa, da sanin Annabinsa Muhammad (SAW). Sheikh Muhammad ibn Abdul-Wahhab ya rubuta ta cikin salon mai sauki don kowa ya fahimta.',
                'table_of_contents': ['Gabatarwa', 'Mas\'aloli Hudu na Wajibi', 'Tushe na 1: Sanin Ubangijinka', 'Tushe na 2: Sanin Addinin Musulunci', 'Tushe na 3: Sanin Annabin ku Muhammad (SAW)', 'Imani da Ranar Tashin Kiyama', 'Hukuncin wanda ya ki Tauhidi'],
                'tags': ['tushe uku', 'usul thalatha', 'akida', 'asali', 'muhammad ibn abdulwahhab', 'three principles'],
                'language': 'ha', 'year': 1750, 'status': 'published', 'approved': True,
                'seo_slug': 'tushe-uku-da-dalillansu',
                'seo_title': 'Tushe Uku da Dalillansu - Hausa',
                'seo_description': 'Tushe uku da kowane musulmi ya kamata ya sani: Sanin Allah, sanin addini, da sanin Annabi Muhammad (SAW).',
                'view_count': 670, 'download_count': 220,
            },
            {
                'title': 'كشف الشبهات',
                'title_hausa': 'Kashfus Shubuhat - Kawar da Shakku-Shakku',
                'author': 'محمد بن عبد الوهاب',
                'category': cats['aqeedah'],
                'category_specific': 'Tawheed',
                'description': 'Wannan littafi yana amsa shakku-shakku da mutane ke gabatarwa game da tauhidi da shirka. Ya bayyana hujjojin wadanda ke kare shirka kuma ya karya su da dalilai daga Alkur\'ani da Sunnah. Littafi ne gajere amma mai karfi a hujja.',
                'table_of_contents': ['Gabatarwa', 'Shubhar Farko: Ceton Masoya Allah', 'Shubhar Biyu: Mu ba mushirikai ba ne', 'Shubhar Uku: Shafa\'ar Annabi', 'Shubhar Hudu: Shirkar zamanin Jahiliyya', 'Shubhar Biyar: Bida\'a da Shirka', 'Kammalawa da Nasaha'],
                'tags': ['kashfus shubuhat', 'shakku', 'shirka', 'tauhidi', 'dalilai', 'hujja', 'doubts'],
                'language': 'ha', 'year': 1750, 'status': 'published', 'approved': True,
                'seo_slug': 'kashfus-shubuhat',
                'seo_title': 'Kashfus Shubuhat - Kawar da Shakku na Hausa',
                'seo_description': 'Kashfus Shubuhat: Amsa shakku-shakku game da tauhidi da shirka ta hanyar dalilai daga Alkur\'ani da Sunnah.',
                'view_count': 540, 'download_count': 180,
            },
            {
                'title': 'لمعة الاعتقاد',
                'title_hausa': 'Lum\'atul I\'tiqad - Hasken Akida',
                'author': 'ابن قدامة المقدسي',
                'category': cats['aqeedah'],
                'category_specific': 'Creed',
                'description': 'Risala ce gajeriya a cikin akidar Ahlus-Sunnah. Ibn Qudama ya bayyana abin da ya wajaba a yi imani da shi game da Allah, mala\'ikunSa, littattafanSa, manzanninSa, da ranar lahira a cikin kalmomi kadan masu ma\'ana.',
                'table_of_contents': ['Siffofin Allah', 'Alkur\'ani Kalmar Allah', 'Ganin Allah', 'Imani da Mala\'iku', 'Imani da Littattafai da Manzanni', 'Kaddara', 'Sahabbai'],
                'tags': ['lumatul itiqad', 'ibn qudama', 'akida', 'sunnah', 'hanbali'],
                'language': 'ha', 'year': 1223, 'status': 'published', 'approved': True,
                'seo_slug': 'lumatul-itiqad',
                'seo_title': 'Lum\'atul I\'tiqad - Ibn Qudama na Hausa',
                'seo_description': 'Risalar akidar Ahlus-Sunnah na Ibn Qudama a harshen Hausa.',
                'view_count': 380, 'download_count': 120,
            },

            # ══════════════════════════════════════════
            # الحديث - HADITH (5 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'رياض الصالحين',
                'title_hausa': 'Riyad al-Salihin - Lambuna Salihai',
                'author': 'الإمام النووي',
                'translator': 'مجموعة من العلماء',
                'category': cats['hadith'],
                'category_specific': 'Collections',
                'description': 'Tarin hadisai masu mahimmanci da Imam al-Nawawi ya tattara. Ya kunshi hadisai 1,900 da aka raba cikin surori 372 a cikin babi 19. Yana koyar da kyawawan halaye, ibada, da rayuwar musulmi ta yau da kullum. An zabi hadisai sahihai kacal daga Bukhari, Muslim, da sauransu.',
                'table_of_contents': ['Babi na 1: Niyyah da Ikhlasi', 'Babi na 2: Tuba', 'Babi na 3: Hakuri da Juriya', 'Babi na 4: Gaskiya', 'Babi na 5: Sanya Ido akan Ayyuka', 'Babi na 6: Taqwa - Tsoron Allah', 'Babi na 7: Yakini da Tawakkul', 'Babi na 8: Istiqama - Daidaito', 'Babi na 9: Tunani a Ayyukan Allah', 'Babi na 10: Gaggawar Aikin Alheri', 'Babi na 11: Mujahada - Gwagwarmaya', 'Babi na 12: Karfafa gwiwa a kan Ibada'],
                'tags': ['hadisi', 'nawawi', 'salihai', 'ahlaki', 'ibada', 'riyad', 'sahih', 'gardens', 'righteous'],
                'language': 'ha', 'year': 1277, 'status': 'published', 'approved': True,
                'seo_slug': 'riyad-al-salihin',
                'seo_title': 'Riyad al-Salihin - Lambuna Salihai na Hausa',
                'seo_description': 'Tarin hadisai 1,900 na Imam Nawawi. Koyarwar ibada da kyawawan halaye a rayuwar musulmi.',
                'view_count': 1580, 'download_count': 620,
            },
            {
                'title': 'الأربعون النووية',
                'title_hausa': 'Hadisai Arba\'in na Nawawi',
                'author': 'الإمام النووي',
                'translator': 'الشيخ محمد ناصر الدين الهوساوي',
                'category': cats['hadith'],
                'category_specific': 'Forty Hadith',
                'description': 'Hadisai arba\'in da biyu (42) da Imam Nawawi ya tattara, wadanda suka hada da manyan ka\'idojin addinin Musulunci. Kowane hadisi yana dauke da babban darasi na rayuwar musulmi. Wannan littafi shi ne farkon abin da dalibi ya kamata ya haddace.',
                'table_of_contents': ['Hadisi na 1: Ayyuka da Niyyoyi', 'Hadisi na 2: Hadishin Jibril - Musulunci, Imani, Ihsani', 'Hadisi na 3: Ginshikan Musulunci Biyar', 'Hadisi na 4: Halitta cikin Mahaifa', 'Hadisi na 5: Kin Bid\'a', 'Hadisi na 6: Halal da Haram da Shakku', 'Hadisi na 7: Addini Nasiha ne', 'Hadisi na 8: Tsarkake Jinin Musulmi', 'Hadisi na 9: Abin da aka Haramta da aka Wajabta'],
                'tags': ['arbain', 'nawawi', 'hadisi', 'ainihin hadisai', 'kaidoji', 'asali', 'forty hadith', 'haddace'],
                'language': 'ha', 'year': 1277, 'status': 'published', 'approved': True,
                'seo_slug': 'hadisai-arbain-nawawi',
                'seo_title': 'Hadisai Arba\'in na Nawawi - Hausa',
                'seo_description': 'Hadisai 42 na Imam Nawawi - manyan ka\'idojin addinin Musulunci a harshen Hausa.',
                'view_count': 2100, 'download_count': 850,
            },
            {
                'title': 'بلوغ المرام',
                'title_hausa': 'Bulughul Maram - Cimma Burin Ilimi',
                'author': 'ابن حجر العسقلاني',
                'category': cats['hadith'],
                'category_specific': 'Ahkam',
                'description': 'Tarin hadisai na hukunce-hukunce (ahkam) da Hafiz Ibn Hajar al-Asqalani ya tattara. Ya kunshi hadisai 1,596 da malamai ke amfani da su wajen fitar da hukunce-hukuncen fikihu. Kowane hadisi an ambaci matsayinsa (sahih, hasan, daif).',
                'table_of_contents': ['Kitabut Tahara: Tsarki da Wanke-wanke', 'Kitabus Salah: Sallah', 'Kitabul Jana\'iz: Hukunce-hukuncen Mutuwa', 'Kitabuz Zakah: Zakka', 'Kitabus Siyam: Azumi', 'Kitabul Hajj: Aikin Hajji', 'Kitabul Buyu\': Ciniki da Kasuwanci', 'Kitabun Nikah: Aure da Saki', 'Kitabul Jinayat: Laifuka', 'Kitabul Jihad: Jihadi'],
                'tags': ['bulughul maram', 'ibn hajar', 'ahkam', 'fikihu', 'hadisi', 'hukunce', 'asqalani'],
                'language': 'ha', 'year': 1449, 'status': 'published', 'approved': True,
                'seo_slug': 'bulughul-maram',
                'seo_title': 'Bulughul Maram - Ibn Hajar na Hausa',
                'seo_description': 'Tarin hadisai 1,596 na hukunce-hukunce na Ibn Hajar al-Asqalani a harshen Hausa.',
                'view_count': 920, 'download_count': 340,
            },
            {
                'title': 'صحيح البخاري',
                'title_hausa': 'Sahihul Bukhari',
                'author': 'الإمام البخاري',
                'translator': 'لجنة الترجمة الهوسوية',
                'category': cats['hadith'],
                'category_specific': 'Sahih Collection',
                'description': 'Mafi ingancin littafin hadisi bayan Alkur\'ani mai girma. Imam Bukhari ya shafe shekaru 16 yana tattara hadisai sahihai. Ya kunshi hadisai 7,275 (ba tare da maimaita ba: 2,602). Wannan shine ginshikin ilimin hadisi a Musulunci.',
                'table_of_contents': ['Farkon Wahayi', 'Littafin Imani', 'Littafin Ilimi', 'Littafin Alwala', 'Littafin Sallah', 'Littafin Lokutan Sallah', 'Littafin Azumi', 'Littafin Hajji', 'Littafin Jihadi', 'Littafin Ciniki'],
                'tags': ['bukhari', 'sahih', 'hadisi', 'ingantaccen hadisi', 'sunna', 'authentic'],
                'language': 'ha', 'year': 846, 'status': 'published', 'approved': True,
                'seo_slug': 'sahihul-bukhari',
                'seo_title': 'Sahihul Bukhari - Ingantattun Hadisai na Hausa',
                'seo_description': 'Sahihul Bukhari: Mafi ingancin littafin hadisi. Hadisai 7,275 sahihai a harshen Hausa.',
                'view_count': 3200, 'download_count': 1100,
            },
            {
                'title': 'عمدة الأحكام',
                'title_hausa': 'Umdatul Ahkam',
                'author': 'عبد الغني المقدسي',
                'category': cats['hadith'],
                'category_specific': 'Ahkam',
                'description': 'Tarin hadisai na hukunce-hukunce da Abdul-Ghani al-Maqdisi ya tattara daga Sahih Bukhari da Muslim kacal. Duk hadisai a cikinsa muttafaqun alaih ne (Bukhari da Muslim sun yarda). Littafi ne mai sauki ga dalibai.',
                'table_of_contents': ['Kitabut Tahara', 'Kitabus Salah', 'Kitabuz Zakah', 'Kitabus Siyam', 'Kitabul Hajj', 'Kitabul Buyu\'', 'Kitabul Qada (Shari\'a)'],
                'tags': ['umdatul ahkam', 'maqdisi', 'ahkam', 'bukhari', 'muslim', 'muttafaq'],
                'language': 'ha', 'year': 1203, 'status': 'published', 'approved': True,
                'seo_slug': 'umdatul-ahkam',
                'seo_title': 'Umdatul Ahkam - Hadisai Ahkam na Hausa',
                'seo_description': 'Hadisai ingantattun na hukunce-hukunce daga Bukhari da Muslim a harshen Hausa.',
                'view_count': 450, 'download_count': 160,
            },

            # ══════════════════════════════════════════
            # الفقه - FIQH (4 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'فقه السنة',
                'title_hausa': 'Fiqhus Sunnah - Fikihu bisa Sunnah',
                'author': 'السيد سابق',
                'translator': 'الشيخ أمينو إبراهيم داورا',
                'category': cats['fiqh'],
                'category_specific': 'General Fiqh',
                'description': 'Littafi ne da ya tattara hukunce-hukuncen fikihu bisa dalilai daga Alkur\'ani da Sunnah kai tsaye. Ya shafi tahara, sallah, azumi, zakka, hajji, da mu\'amalat. Ya dace da kowane musulmi don fahimtar addininsa bisa dalili.',
                'table_of_contents': ['Tahara: Wanke-wanke da Alwala', 'Sallah: Salloli Biyar da Sharuddan su', 'Sallar Jama\'a da Masallaci', 'Sallar Jumu\'a', 'Sallolin Nafila', 'Azumi: Watan Ramadan', 'Zakka: Nau\'oin Zakka da Adadin su', 'Hajji da Umra', 'Jana\'iza da Hukuncin Mutuwa', 'Nikah: Aure a Musulunci'],
                'tags': ['fikihu', 'sunnah', 'sayyid sabiq', 'ibada', 'sallah', 'azumi', 'zakka', 'hajji', 'general fiqh'],
                'language': 'ha', 'year': 1945, 'status': 'published', 'approved': True,
                'seo_slug': 'fiqhus-sunnah',
                'seo_title': 'Fiqhus Sunnah - Fikihu bisa Sunnah na Hausa',
                'seo_description': 'Fikihu bisa dalilai daga Alkur\'ani da Sunnah. Hukunce-hukuncen ibada a harshen Hausa.',
                'view_count': 1350, 'download_count': 480,
            },
            {
                'title': 'منار السبيل',
                'title_hausa': 'Manarus Sabil - Hasken Hanya',
                'author': 'ابن ضويان',
                'category': cats['fiqh'],
                'category_specific': 'Hanbali Fiqh',
                'description': 'Sharhin littafin "Dalilul Talib" a mazhabar Hanbali. Yana bayyana hukunce-hukuncen fikihu tare da ambaton dalilai daga hadisai da Alkur\'ani. Littafi ne mai muhimmanci ga daliban fikihu.',
                'table_of_contents': ['Kitabut Tahara', 'Kitabus Salah', 'Kitabuz Zakah', 'Kitabus Siyam', 'Kitabul Hajj', 'Kitabul Buyu\'', 'Kitabun Nikah', 'Kitabul Jinayat'],
                'tags': ['manarus sabil', 'hanbali', 'fikihu', 'dalilai', 'ibn duwayyan', 'madhhab'],
                'language': 'ha', 'year': 1900, 'status': 'published', 'approved': True,
                'seo_slug': 'manarus-sabil',
                'seo_title': 'Manarus Sabil - Fikihu Hanbali na Hausa',
                'seo_description': 'Sharhin fikihu na mazhabar Hanbali tare da dalilai daga Alkur\'ani da Sunnah.',
                'view_count': 720, 'download_count': 250,
            },
            {
                'title': 'الملخص الفقهي',
                'title_hausa': 'Mulakhkhas Fiqhi - Takaitaccen Fikihu',
                'author': 'صالح بن فوزان الفوزان',
                'category': cats['fiqh'],
                'category_specific': 'Comprehensive Fiqh',
                'description': 'Takaitaccen littafin fikihu da Sheikh Fawzan ya rubuta. Ya hada da dukan abwab na fikihu cikin salon mai sauki da misalai na zamani. Ya dace da masu farawa da kuma masu bita.',
                'table_of_contents': ['Ibadoji: Tahara da Sallah', 'Ibadoji: Zakka da Azumi da Hajji', 'Mu\'amalat: Ciniki', 'Mu\'amalat: Musharaka da Bashi', 'Nikah da Saki', 'Abinci da Abin Sha', 'Jinayat da Hukunce'],
                'tags': ['mulakhkhas', 'fawzan', 'fikihu', 'takaitacce', 'ibada', 'muamalat'],
                'language': 'ha', 'year': 2001, 'status': 'published', 'approved': True,
                'seo_slug': 'mulakhkhas-fiqhi',
                'seo_title': 'Mulakhkhas Fiqhi - Takaitaccen Fikihu na Hausa',
                'seo_description': 'Takaitaccen fikihu na Sheikh Fawzan. Dukan abwab na fikihu cikin salon mai sauki.',
                'view_count': 610, 'download_count': 200,
            },
            {
                'title': 'صفة صلاة النبي',
                'title_hausa': 'Siffar Sallar Annabi (SAW)',
                'author': 'محمد ناصر الدين الألباني',
                'category': cats['fiqh'],
                'category_specific': 'Salah',
                'description': 'Bayyanin yadda Annabi (SAW) yake sallah daga farko zuwa karshe bisa hadisai ingantattun. Sheikh Albani ya tattara dukan hadisai game da sallah ya tsara su cikin tsari. Duk musulmi ya kamata ya karanta wannan littafi.',
                'table_of_contents': ['Niyyah da Takbira', 'Tsayuwa da Karatun Fatiha', 'Ruku\'u', 'Sujuda', 'Tashahhud', 'Sallama', 'Azkar Bayan Sallah', 'Sallar Nafila', 'Sallar Musafiri'],
                'tags': ['sallah', 'albani', 'siffar sallah', 'annabi', 'ibada', 'prayer', 'hadisi'],
                'language': 'ha', 'year': 1957, 'status': 'published', 'approved': True,
                'seo_slug': 'siffar-sallar-annabi',
                'seo_title': 'Siffar Sallar Annabi - Albani na Hausa',
                'seo_description': 'Yadda Annabi Muhammad (SAW) yake sallah bisa hadisai sahihai na Sheikh Albani.',
                'view_count': 1800, 'download_count': 700,
            },

            # ══════════════════════════════════════════
            # التفسير - TAFSIR (3 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'تفسير ابن كثير',
                'title_hausa': 'Tafsirin Ibn Kathir',
                'author': 'ابن كثير',
                'translator': 'مجموعة من المترجمين',
                'category': cats['tafsir'],
                'category_specific': 'Complete Tafsir',
                'description': 'Daya daga cikin shahararrun tafsirai na Alkur\'ani mai girma. Ibn Kathir ya yi amfani da hanyar tafsirin Alkur\'ani da Alkur\'ani, sannan hadisi, sannan maganganun Sahabbai da Tabi\'in. Ya kunshi mujalladi 8 kuma malaman suka yarda da shi.',
                'table_of_contents': ['Suratul Fatiha', 'Suratul Baqara', 'Suratu Ali Imran', 'Suratun Nisa\'i', 'Suratul Ma\'ida', 'Suratul An\'am', 'Suratul A\'raf', 'Suratul Anfal', 'Suratut Tawba', 'Suratu Yunus'],
                'tags': ['tafsiri', 'ibn kathir', 'alkurani', 'fassara', 'quran', 'tafsir', 'exegesis'],
                'language': 'ha', 'year': 1370, 'status': 'published', 'approved': True,
                'seo_slug': 'tafsirin-ibn-kathir',
                'seo_title': 'Tafsirin Ibn Kathir - Fassarar Alkur\'ani na Hausa',
                'seo_description': 'Tafsirin Alkur\'ani na Ibn Kathir a harshen Hausa. Fassara da bayani mai zurfi game da kowane aya.',
                'view_count': 2800, 'download_count': 950,
            },
            {
                'title': 'تفسير السعدي',
                'title_hausa': 'Tafsirin Sa\'adi - Taisir Karimir Rahman',
                'author': 'عبد الرحمن بن ناصر السعدي',
                'category': cats['tafsir'],
                'category_specific': 'Simplified Tafsir',
                'description': 'Tafsiri mai sauki da fili wanda Sheikh Sa\'adi ya rubuta. Yana bayyana ma\'anonin ayoyi cikin saukin fahimta ba tare da tsawon magana ba. Ya dace da kowa musamman wadanda ba masana ba. Mujalladi daya kacal amma ya kammala dukan Alkur\'ani.',
                'table_of_contents': ['Muqaddima', 'Suratul Fatiha', 'Suratul Baqara (Kashi na 1)', 'Suratul Baqara (Kashi na 2)', 'Suratu Ali Imran', 'Suratun Nisa\'i', 'Suratul Ma\'ida', 'Suratul An\'am'],
                'tags': ['tafsiri', 'saadi', 'taisir', 'alkurani', 'sauki', 'simplified', 'quran'],
                'language': 'ha', 'year': 1957, 'status': 'published', 'approved': True,
                'seo_slug': 'tafsirin-saadi',
                'seo_title': 'Tafsirin Sa\'adi - Taisir na Hausa',
                'seo_description': 'Tafsirin Alkur\'ani mai sauki na Sheikh Sa\'adi. Fassara cikin saukin fahimta a harshen Hausa.',
                'view_count': 1450, 'download_count': 520,
            },
            {
                'title': 'تفسير الجلالين',
                'title_hausa': 'Tafsirin Jalalain',
                'author': 'جلال الدين المحلي وجلال الدين السيوطي',
                'category': cats['tafsir'],
                'category_specific': 'Concise Tafsir',
                'description': 'Tafsiri ne gajere wanda Imaman biyu suka rubuta: Jalaluddin al-Mahalli (ya fara) da Jalaluddin as-Suyuti (ya kammala). Ana amfani da shi a makarantun Musulunci na gargajiya a kasashen Hausa tun dauri.',
                'table_of_contents': ['Suratul Fatiha', 'Suratul Baqara', 'Suratu Ali Imran', 'Suratun Nisa\'i'],
                'tags': ['tafsiri', 'jalalain', 'mahalli', 'suyuti', 'alkurani', 'gajere'],
                'language': 'ha', 'year': 1505, 'status': 'published', 'approved': True,
                'seo_slug': 'tafsirin-jalalain',
                'seo_title': 'Tafsirin Jalalain - Hausa',
                'seo_description': 'Tafsirin Jalalain: Gajeren tafsirin Alkur\'ani da Imaman biyu suka rubuta.',
                'view_count': 680, 'download_count': 230,
            },

            # ══════════════════════════════════════════
            # السيرة - SEERAH (3 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'الرحيق المختوم',
                'title_hausa': 'Rahiqul Makhtum - Turaren da aka Rufe',
                'author': 'صفي الرحمن المباركفوري',
                'translator': 'الشيخ أبو بكر سولي',
                'category': cats['seerah'],
                'category_specific': 'Prophet Biography',
                'description': 'Mafi shahararren littafin sirar Annabi Muhammad (SAW) a zamaninmu. Ya lashe lambar yabo ta farko a gasar duniya ta sirar Annabi ta Rabitat al-Alam al-Islami a shekarar 1979. Yana bayyana rayuwar Annabi tun daga haihuwarsa har zuwa rasuwarsa cikin bayani mai zurfi.',
                'table_of_contents': ['Larabawa da Duniya Kafin Musulunci', 'Nasabar Annabi (SAW) da Haihuwarsa', 'Yarinta da Samartakarsa', 'Aurensa da Khadijah', 'Farkon Wahayi', 'Da\'awa a Asirce (Shekara 3)', 'Da\'awa a Bayyane', 'Azabar Mushirikai', 'Hijira zuwa Habasha', 'Hijira zuwa Madina', 'Yakin Badr al-Kubra', 'Yakin Uhud', 'Yakin Khandaq', 'Sulhun Hudaibiyya', 'Fathin Makka', 'Yakin Hunain', 'Hajjatul Wada\'i', 'Rasuwar Annabi (SAW)'],
                'tags': ['sira', 'annabi', 'muhammad', 'rahiqul makhtum', 'tarihi', 'prophet', 'biography', 'sealed nectar'],
                'language': 'ha', 'year': 1979, 'status': 'published', 'approved': True,
                'seo_slug': 'rahiqul-makhtum',
                'seo_title': 'Rahiqul Makhtum - Sirar Annabi na Hausa',
                'seo_description': 'Shahararren littafin sirar Annabi Muhammad (SAW). Ya lashe lambar yabo ta duniya a 1979.',
                'view_count': 2500, 'download_count': 880,
            },
            {
                'title': 'نور اليقين في سيرة سيد المرسلين',
                'title_hausa': 'Nurul Yaqin - Hasken Yakini',
                'author': 'محمد الخضري بك',
                'category': cats['seerah'],
                'category_specific': 'Prophet Biography',
                'description': 'Littafin sira ne mai sauki da fili da ya dace da dalibai da masu farawa. Ya bayyana rayuwar Annabi (SAW) cikin tsari mai kyau tare da darussa masu muhimmanci. Ana karantar da shi a makarantu da jami\'o\'i.',
                'table_of_contents': ['Nasabar Annabi (SAW)', 'Haihuwa da Yarinta', 'Matasa da Aure', 'Farkon Sako', 'Gwaje-gwaje a Makka', 'Hijira', 'Kafa Jihar Madina', 'Yakokin Annabi', 'Fathin Makka', 'Wafatin Annabi'],
                'tags': ['nurul yaqin', 'sira', 'annabi', 'khudari', 'sirar manzo', 'sauki'],
                'language': 'ha', 'year': 1935, 'status': 'published', 'approved': True,
                'seo_slug': 'nurul-yaqin-sira',
                'seo_title': 'Nurul Yaqin - Sirar Annabi na Hausa',
                'seo_description': 'Sirar Annabi Muhammad (SAW) mai sauki a harshen Hausa na Sheikh Khudari.',
                'view_count': 980, 'download_count': 350,
            },
            {
                'title': 'زاد المعاد في هدي خير العباد',
                'title_hausa': 'Zadul Ma\'ad - Guzurin Lahira',
                'author': 'ابن القيم الجوزية',
                'category': cats['seerah'],
                'category_specific': 'Prophet Guidance',
                'description': 'Littafi ne mai girma da ya hada sirar Annabi (SAW) tare da fikihu da hukunce-hukuncen da ake ciro daga rayuwarsa. Ibn al-Qayyim ya bayyana yadda Annabi yake mu\'amala da kowane yanayi na rayuwa: ibada, yaki, lafiya, abinci, tafiya, aure, da sauransu.',
                'table_of_contents': ['Hadin Annabi a Ibada', 'Hadin Annabi a Sallah', 'Hadin Annabi a Azumi', 'Hadin Annabi a Hajji', 'Hadin Annabi a Jihadi', 'Hadin Annabi a Magani', 'Hadin Annabi a Ciniki', 'Hadin Annabi a Aure'],
                'tags': ['zadul maad', 'ibn qayyim', 'sira', 'fikihu', 'hadin annabi', 'guidance'],
                'language': 'ha', 'year': 1350, 'status': 'published', 'approved': True,
                'seo_slug': 'zadul-maad',
                'seo_title': 'Zadul Ma\'ad - Ibn al-Qayyim na Hausa',
                'seo_description': 'Hadin Annabi (SAW) a kowane fanni na rayuwa: ibada, lafiya, mu\'amala. Na Ibn al-Qayyim.',
                'view_count': 760, 'download_count': 280,
            },

            # ══════════════════════════════════════════
            # التزكية - TAZKIYAH (2 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'مختصر منهاج القاصدين',
                'title_hausa': 'Mukhtasar Minhajul Qasidin',
                'author': 'ابن قدامة المقدسي',
                'category': cats['tazkiyah'],
                'category_specific': 'Purification',
                'description': 'Takaitaccen littafi ne na tarbiyya da tsarkake zuciya. Ya tattaro mafi muhimmanci daga littafin "Ihya Ulumiddin" na Imam Ghazali, amma an tsarkake shi daga hadisan da ba su da tushe. Ya koyar da yadda ake gyara zuciya da kyawawan halaye.',
                'table_of_contents': ['Ilimi da Falallarsa', 'Akida', 'Asirin Tsarki', 'Asirin Sallah', 'Asirin Zakka', 'Asirin Azumi', 'Asirin Hajji', 'Karatun Alkur\'ani', 'Zikiri da Addu\'a', 'Tsarin Lokaci', 'Tuba da Istighfari', 'Hakuri da Godiya', 'Tsoron Allah da Fatan Sa'],
                'tags': ['tazkiyah', 'tarbiyya', 'zuciya', 'minhaj', 'ibn qudama', 'ihya', 'purification', 'soul'],
                'language': 'ha', 'year': 1250, 'status': 'published', 'approved': True,
                'seo_slug': 'mukhtasar-minhajul-qasidin',
                'seo_title': 'Mukhtasar Minhajul Qasidin - Hausa',
                'seo_description': 'Littafin tarbiyya da tsarkake zuciya na Ibn Qudama. Gyaran zuciya da kyawawan halaye.',
                'view_count': 550, 'download_count': 190,
            },
            {
                'title': 'الداء والدواء',
                'title_hausa': 'Ciwo da Magani - Amsar Wafi',
                'author': 'ابن القيم الجوزية',
                'category': cats['tazkiyah'],
                'category_specific': 'Spiritual Diseases',
                'description': 'Littafi ne game da cututtukan zuciya da maganinsu. Ibn al-Qayyim ya bayyana yadda zunubi ke lalata zuciya da jiki da zamantakewa, sannan ya nuna hanyar magance su ta hanyar tuba da tsoron Allah.',
                'table_of_contents': ['Illa\'ar Zunubi', 'Tasirin Zunubi a Zuciya', 'Tasirin Zunubi a Jiki', 'Tasirin Zunubi a Rayuwa', 'Tuba: Maganin Zunubi', 'Du\'a\'i da Zikiri', 'Hakuri da Tawakkul'],
                'tags': ['ciwo', 'magani', 'ibn qayyim', 'tazkiyah', 'zunubi', 'tuba', 'zuciya'],
                'language': 'ha', 'year': 1340, 'status': 'published', 'approved': True,
                'seo_slug': 'ciwo-da-magani',
                'seo_title': 'Ciwo da Magani - Ibn al-Qayyim na Hausa',
                'seo_description': 'Cututtukan zuciya da maganinsu na Ibn al-Qayyim a harshen Hausa.',
                'view_count': 420, 'download_count': 150,
            },

            # ══════════════════════════════════════════
            # اللغة العربية - ARABIC (2 كتب)
            # ══════════════════════════════════════════
            {
                'title': 'الآجرومية',
                'title_hausa': 'Al-Ajurumiyya - Nahawun Larabci',
                'author': 'ابن آجروم',
                'category': cats['arabic'],
                'category_specific': 'Grammar',
                'description': 'Mafi shahararren littafin koyon nahawun (grammar) Larabci ga masu farawa. Karami ne amma ya tattara manyan ka\'idojin da ake bukata don fahimtar harshen Larabci. Dukan makarantu na Musulunci suna karantar da shi.',
                'table_of_contents': ['Nau\'oin Kalmomi: Ismu, Fi\'lu, Harfu', 'Alamomin I\'rab', 'Marfu\'at: Fa\'il da Mubtada', 'Mansubat: Maf\'ul bih', 'Majrurat: Hurufil Jarr', 'Tawabi\': Na\'at, Atf, Tawkid, Badal'],
                'tags': ['ajurumiyya', 'nahawu', 'larabci', 'grammar', 'arabic', 'koyo', 'beginner'],
                'language': 'ha', 'year': 1309, 'status': 'published', 'approved': True,
                'seo_slug': 'al-ajurumiyya',
                'seo_title': 'Al-Ajurumiyya - Koyon Larabci na Hausa',
                'seo_description': 'Littafin koyon nahawun Larabci ga masu farawa a harshen Hausa. Ka\'idojin grammar.',
                'view_count': 1100, 'download_count': 400,
            },
            {
                'title': 'القواعد الأربع',
                'title_hausa': 'Ka\'idoji Hudu - Al-Qawa\'id al-Arba\'',
                'author': 'محمد بن عبد الوهاب',
                'category': cats['aqeedah'],
                'category_specific': 'Tawheed',
                'description': 'Risala ce gajeriya da ta kunshi ka\'idoji hudu na bambance tsakanin Musulunci da shirka. Ta bayyana yadda mushirikai na da suka kasance da kuma yadda za a gane shirka ta zamani.',
                'table_of_contents': ['Gabatarwa da Du\'a\'i', 'Ka\'ida ta 1: Kafiran Annabi sun yarda Allah ne Mahalicci', 'Ka\'ida ta 2: Sun nemi kusanci ga Allah ne', 'Ka\'ida ta 3: Sun bambanta cikin abin bauta', 'Ka\'ida ta 4: Mushirikai na zamaninmu sun fi na da'],
                'tags': ['qawaid arba', 'kaidoji hudu', 'tauhidi', 'shirka', 'muhammad ibn abdulwahhab'],
                'language': 'ha', 'year': 1750, 'status': 'published', 'approved': True,
                'seo_slug': 'kaidoji-hudu',
                'seo_title': 'Ka\'idoji Hudu - Al-Qawa\'id al-Arba na Hausa',
                'seo_description': 'Ka\'idoji hudu na bambance Musulunci da shirka na Sheikh Muhammad ibn Abdul-Wahhab.',
                'view_count': 490, 'download_count': 170,
            },

            # ══════════════════════════════════════════
            # أصول الفقه - USUL AL-FIQH (1 كتاب)
            # ══════════════════════════════════════════
            {
                'title': 'الأصول من علم الأصول',
                'title_hausa': 'Usul min Ilmil Usul',
                'author': 'محمد بن صالح العثيمين',
                'category': cats['usul-al-fiqh'],
                'category_specific': 'Principles',
                'description': 'Gabatarwa mai sauki cikin ilimin usulul fikihu. Sheikh Uthaymin ya rubuta shi a salon da ya dace da dalibai don fahimtar yadda ake fitar da hukunce daga Alkur\'ani da Sunnah. Ya bayyana: hukunce-hukunce, dalilai, naskhi, ijtihadi, da taqlidi.',
                'table_of_contents': ['Gabatarwa: Ma\'anar Usulul Fikihu', 'Hukunce-hukuncen Shari\'a: Wajib, Haram, Makruh...', 'Dalili na 1: Alkur\'ani', 'Dalili na 2: Sunnah', 'Dalili na 3: Ijma\'i', 'Dalili na 4: Qiyas', 'Naskhi: Soke Hukunci', 'Ta\'arud da Tarjih: Sabani tsakanin Dalilai', 'Ijtihadi da Taqlidi'],
                'tags': ['usul', 'fikihu', 'kaidoji', 'uthaymin', 'ijtihad', 'principles', 'methodology'],
                'language': 'ha', 'year': 1986, 'status': 'published', 'approved': True,
                'seo_slug': 'usul-min-ilmil-usul',
                'seo_title': 'Usul min Ilmil Usul - Uthaymin na Hausa',
                'seo_description': 'Ka\'idojin fitar da hukunce-hukunce na Sheikh Uthaymin a harshen Hausa. Ilimin usulul fikihu.',
                'view_count': 380, 'download_count': 130,
            },
        ]

        created = 0
        updated = 0
        for data in books_data:
            slug = data.pop('seo_slug')
            obj, is_new = Book.objects.update_or_create(seo_slug=slug, defaults=data)
            if is_new:
                created += 1
            else:
                updated += 1

        total = Book.objects.count()
        published = Book.objects.filter(status='published').count()
        self.stdout.write(self.style.SUCCESS(
            f'✅ Done! Created: {created} | Updated: {updated} | Total: {total} | Published: {published}'
        ))
